# Generated by Django 5.1.2 on 2024-10-25 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managerDashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='event',
            name='updated_at',
        ),
    ]
