# Generated by Django 5.1.2 on 2024-10-26 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('userPreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'role': 'RESTAURANT_OWNER'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_restaurant', to='main.userprofile'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(related_name='preferences', to='userPreferences.tag'),
        ),
    ]
