# Generated by Django 5.1.2 on 2024-10-26 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='restaurant',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='menu',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='menus',
        ),
        migrations.RemoveField(
            model_name='wishlist',
            name='user',
        ),
        migrations.DeleteModel(
            name='Announcement',
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
