# Generated by Django 5.1.1 on 2024-10-25 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_event_created_by_alter_userprofile_role_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
