# Generated by Django 5.1.1 on 2024-10-26 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userprofile_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='menus',
        ),
    ]
