# Generated by Django 5.1.1 on 2024-10-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_tag_menus'),
        ('userPreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='preferences',
            field=models.ManyToManyField(related_name='preferences', to='userPreferences.tag'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
