# Generated by Django 5.1.2 on 2024-10-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catatan', models.TextField()),
                ('status', models.CharField(choices=[('BELUM', 'Belum Pernah Dibeli'), ('SUDAH', 'Sudah Pernah Dibeli')], default='BELUM', max_length=6)),
            ],
            options={
                'verbose_name': 'Wishlist',
                'verbose_name_plural': 'Wishlists',
            },
        ),
    ]
