# Generated by Django 5.1.2 on 2024-10-27 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goyangNanti', '0001_initial'),
        ('main', '0001_initial'),
        ('menuResto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='menuResto.menu'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(limit_choices_to={'role': 'CUSTOMER'}, on_delete=django.db.models.deletion.CASCADE, related_name='goyangnanti_wishlists', to='main.userprofile'),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'menu')},
        ),
    ]
