# Generated by Django 5.1.2 on 2024-10-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goyangNanti', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='catatan',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
