# Generated by Django 5.1 on 2024-10-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulasGoyangan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='last_edited',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
